name: Build Status - Development
on:
  push:
    branches:
    - development
  pull_request:
    branches:
    - development
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - name: Branch Checkout
      uses: actions/checkout@v2.4.0
    - name: Set Custom NuGet Packages
      run: |
        dotnet nuget add source ${env:PrivateNuGetUrl} -n "SBRW Launcher Libraries" -u ${env:GHUserName} -p ${env:Password} --store-password-in-clear-text
      env:
        PrivateNuGetUrl: ${{ secrets.SBRW_LIBRARIES_LAUNCHER_NUGET_URL }}
        GHUserName: ${{ secrets.SBRW_LIBRARIES_LAUNCHER_USERNAME }}
        Password: ${{ secrets.SBRW_LIBRARIES_LAUNCHER_OUTHTOKEN }}
    - name: Restore Custom NuGet Packages
      run: dotnet restore "Source\SBRW.Svg.csproj" --ignore-failed-sources      
    - name: Build
      run: dotnet build "Source\SBRW.Svg.csproj" --configuration Release